// Generates supabase/seed_updates.sql — UPDATE statements that push EDITS to
// existing global starter cards (and deck metadata) into a live database.
//
// Unlike seed.sql (insert-only, idempotent provisioning), this overwrites the
// metadata columns of cards that ALREADY exist, matched by
// (deck slug, lower(spanish_text), lower(english_text)). It never inserts or
// deletes — pair additions/removals still go through generate_seed.cjs/seed.sql.
//
// Run: node supabase/scripts/generate_update.cjs
//      psql "<connection string>" -f supabase/seed_updates.sql
const fs = require('fs');
const path = require('path');
const { optText, normCard, pairKey } = require('./lib/cards.cjs');
const SEED_DECKS = require('./lib/seed_decks.cjs');

const DATA_DIR = path.resolve(__dirname, '../seed_data');
const OUT = path.resolve(__dirname, '../seed_updates.sql');

// Same source ordering + merge/dedup as generate_seed.cjs.
const sources = [...SEED_DECKS];
const files = fs.readdirSync(DATA_DIR).filter(f => /^deck_expansions.*\.json$/.test(f)).sort();
for (const f of files) {
  const payload = JSON.parse(fs.readFileSync(path.join(DATA_DIR, f), 'utf8'));
  if (!Array.isArray(payload)) throw new Error(f + ' must be a list');
  sources.push(...payload);
}

const decks = new Map();
for (const src of sources) {
  const slug = optText(src.slug);
  const title = optText(src.title);
  const description = optText(src.description);
  if (!slug || !title || !description) throw new Error('deck missing slug/title/description: ' + slug);
  if (!Array.isArray(src.cards) || src.cards.length === 0) throw new Error('deck has no cards: ' + slug);
  let entry = decks.get(slug);
  if (!entry) {
    entry = { slug, title, description, language_from: optText(src.language_from) || 'es', language_to: optText(src.language_to) || 'en', cards: [], seen: new Set() };
    decks.set(slug, entry);
  }
  for (const c of src.cards) {
    const nc = normCard(c, entry.title);
    const key = pairKey(nc.l1_text, nc.l2_text);
    if (entry.seen.has(key)) continue;
    entry.seen.add(key);
    entry.cards.push(nc);
  }
}

const sq = (s) => s === null ? 'null' : "'" + String(s).replace(/'/g, "''") + "'";
const jsonLit = (obj) => "'" + JSON.stringify(obj).replace(/'/g, "''") + "'";

let sql = `-- AUTO-GENERATED by supabase/scripts/generate_update.cjs — do not edit by hand.\n`;
sql += `-- Pushes EDITS to existing global starter cards into a live DB. Only updates\n`;
sql += `-- rows matched by (deck slug, lower(l1_text), lower(l2_text)); never inserts/deletes.\n\n`;
// UTF-8 payload; force the client encoding so psql on a WIN1252 console
// (Windows default) doesn't choke converting smart quotes/dashes. See
// generate_seed.cjs for the full rationale.
sql += `set client_encoding = 'UTF8';\n\n`;
sql += `begin;\n\n`;

let totalCards = 0;
for (const deck of decks.values()) {
  totalCards += deck.cards.length;
  sql += `-- ${deck.slug} (${deck.cards.length} cards)\n`;

  // Refresh deck metadata (title/description/languages) by slug.
  sql += `update public.decks set\n`;
  sql += `  title = ${sq(deck.title)}, description = ${sq(deck.description)},\n`;
  sql += `  language_from = ${sq(deck.language_from)}, language_to = ${sq(deck.language_to)}\n`;
  sql += `where slug = ${sq(deck.slug)};\n\n`;

  const cardsJson = deck.cards.map(c => ({
    l1_text: c.l1_text,
    l2_text: c.l2_text,
    section_name: c.section_name,
    part_of_speech: c.part_of_speech,
    l2_definition: c.l2_definition,
    l1_translations: c.l1_translations,
    collocations: c.collocations,
    l2_synonyms: c.l2_synonyms,
    example_sentence: c.example_sentence,
    example_l1: c.example_l1,
    example_l2: c.example_l2,
    l2_mnemonic: c.l2_mnemonic,
    l2_cloze_distractors: c.l2_cloze_distractors,
    examples: c.examples,
  }));

  // Overwrite metadata columns on matching existing cards. Identity columns
  // (l1_text/l2_text) and is_enabled/progress are left untouched.
  // l2_mnemonic, l2_cloze_distractors and examples only overwrite when the
  // incoming card actually has a value, so pushing un-enriched seed data never
  // wipes existing mnemonics, curated distractor sets, or example pair sets.
  sql += `update public.cards c set\n`;
  sql += `  section_name = x.section_name, part_of_speech = x.part_of_speech, l2_definition = x.l2_definition,\n`;
  sql += `  l1_translations = coalesce(x.l1_translations, '[]'::jsonb),\n`;
  sql += `  collocations = coalesce(x.collocations, '[]'::jsonb),\n`;
  sql += `  l2_synonyms = coalesce(x.l2_synonyms, '[]'::jsonb),\n`;
  sql += `  example_sentence = x.example_sentence, example_l1 = x.example_l1, example_l2 = x.example_l2,\n`;
  sql += `  l2_mnemonic = coalesce(x.l2_mnemonic, c.l2_mnemonic),\n`;
  sql += `  l2_cloze_distractors = case when jsonb_array_length(coalesce(x.l2_cloze_distractors, '[]'::jsonb)) > 0\n`;
  sql += `                              then x.l2_cloze_distractors else c.l2_cloze_distractors end,\n`;
  sql += `  examples = case when jsonb_array_length(coalesce(x.examples, '[]'::jsonb)) > 0\n`;
  sql += `                  then x.examples else c.examples end\n`;
  sql += `from (select id from public.decks where slug = ${sq(deck.slug)}) dk\n`;
  sql += `cross join jsonb_to_recordset(${jsonLit(cardsJson)}::jsonb) as x(\n`;
  sql += `  l1_text text, l2_text text, section_name text, part_of_speech text, l2_definition text,\n`;
  sql += `  l1_translations jsonb, collocations jsonb, l2_synonyms jsonb, example_sentence text, example_l1 text, example_l2 text, l2_mnemonic text, l2_cloze_distractors jsonb, examples jsonb\n`;
  sql += `)\n`;
  sql += `where c.deck_id = dk.id\n`;
  sql += `  and lower(c.l1_text) = lower(x.l1_text)\n`;
  sql += `  and lower(c.l2_text) = lower(x.l2_text);\n\n`;
}

sql += `commit;\n`;

fs.writeFileSync(OUT, sql, 'utf8');
console.log(`Wrote ${OUT}`);
console.log(`Decks: ${decks.size}, total cards: ${totalCards}, file size: ${(sql.length / 1024).toFixed(1)} KB`);
