// Generates supabase/seed.sql for the global starter decks.
// Faithfully mirrors backend/app/db.py _seed_database: process SEED_DECKS first,
// then the deck_expansions*.json files (sorted by filename), merging by slug and
// de-duplicating cards by (spanish, english) case-insensitively (first wins).
//
// Run: node supabase/scripts/generate_seed.cjs
const fs = require('fs');
const path = require('path');
const { optText, normCard, pairKey } = require('./lib/cards.cjs');
// The 3 hand-authored starter decks live in lib/seed_decks.cjs (shared with the
// AI generator). Card normalization helpers live in lib/cards.cjs.
const SEED_DECKS = require('./lib/seed_decks.cjs');

const DATA_DIR = path.resolve(__dirname, '../seed_data');
const OUT = path.resolve(__dirname, '../seed.sql');

// Build the ordered source list: SEED_DECKS, then expansion files sorted by name.
const sources = [...SEED_DECKS];
const files = fs.readdirSync(DATA_DIR).filter(f => /^deck_expansions.*\.json$/.test(f)).sort();
for (const f of files) {
  const payload = JSON.parse(fs.readFileSync(path.join(DATA_DIR, f), 'utf8'));
  if (!Array.isArray(payload)) throw new Error(f + ' must be a list');
  sources.push(...payload);
}

// Merge by slug, de-dupe cards by (spanish, english).
const decks = new Map(); // slug -> {slug,title,description,language_from,language_to,cards:[],seen:Set}
for (const src of sources) {
  const slug = optText(src.slug);
  const title = optText(src.title);
  const description = optText(src.description);
  if (!slug || !title || !description) throw new Error('deck missing slug/title/description: ' + slug);
  if (!Array.isArray(src.cards) || src.cards.length === 0) throw new Error('deck has no cards: ' + slug);
  let entry = decks.get(slug);
  if (!entry) {
    entry = { slug, title, description, language_from: optText(src.language_from) || 'es', language_to: optText(src.language_to) || 'en', cards: [], seen: new Set() };
    decks.set(slug, entry);
  }
  for (const c of src.cards) {
    const nc = normCard(c, entry.title);
    const key = pairKey(nc.l1_text, nc.l2_text);
    if (entry.seen.has(key)) continue;
    entry.seen.add(key);
    entry.cards.push(nc);
  }
}

const sq = (s) => s === null ? 'null' : "'" + String(s).replace(/'/g, "''") + "'";
const jsonLit = (obj) => "'" + JSON.stringify(obj).replace(/'/g, "''") + "'";

let sql = `-- AUTO-GENERATED by supabase/scripts/generate_seed.cjs — do not edit by hand.\n`;
sql += `-- Global starter decks (user_id IS NULL). Idempotent: safe to re-run.\n\n`;
// This file is UTF-8 (Spanish accents + LLM-generated smart quotes/dashes).
// psql on Windows defaults client_encoding to the console codepage (WIN1252),
// which then fails converting bytes like 0x81/0x9D to the UTF-8 database. Tell
// the server the input is already UTF-8 so the load works from any shell.
sql += `set client_encoding = 'UTF8';\n\n`;
sql += `begin;\n\n`;

let totalCards = 0;
for (const deck of decks.values()) {
  totalCards += deck.cards.length;
  sql += `-- ${deck.slug} (${deck.cards.length} cards)\n`;
  sql += `insert into public.decks (slug, title, description, language_from, language_to)\n`;
  sql += `values (${sq(deck.slug)}, ${sq(deck.title)}, ${sq(deck.description)}, ${sq(deck.language_from)}, ${sq(deck.language_to)})\n`;
  sql += `on conflict (slug) do nothing;\n\n`;

  const cardsJson = deck.cards.map(c => ({
    l1_text: c.l1_text,
    l2_text: c.l2_text,
    section_name: c.section_name,
    part_of_speech: c.part_of_speech,
    l2_definition: c.l2_definition,
    l1_translations: c.l1_translations,
    collocations: c.collocations,
    l2_synonyms: c.l2_synonyms,
    example_sentence: c.example_sentence,
    example_l1: c.example_l1,
    example_l2: c.example_l2,
    l2_mnemonic: c.l2_mnemonic,
    l2_cloze_distractors: c.l2_cloze_distractors,
    examples: c.examples,
  }));

  sql += `insert into public.cards (deck_id, l1_text, l2_text, is_enabled, generation_phase, generation_metadata, section_name, part_of_speech, l2_definition, l1_translations, collocations, l2_synonyms, example_sentence, example_l1, example_l2, l2_mnemonic, l2_cloze_distractors, examples)\n`;
  sql += `select dk.id, x.l1_text, x.l2_text, true, 'refined', '{}'::jsonb, x.section_name, x.part_of_speech, x.l2_definition,\n`;
  sql += `       coalesce(x.l1_translations, '[]'::jsonb), coalesce(x.collocations, '[]'::jsonb), coalesce(x.l2_synonyms, '[]'::jsonb), x.example_sentence, x.example_l1, x.example_l2, x.l2_mnemonic, coalesce(x.l2_cloze_distractors, '[]'::jsonb), coalesce(x.examples, '[]'::jsonb)\n`;
  sql += `from (select id from public.decks where slug = ${sq(deck.slug)}) dk\n`;
  sql += `cross join jsonb_to_recordset(${jsonLit(cardsJson)}::jsonb) as x(\n`;
  sql += `  l1_text text, l2_text text, section_name text, part_of_speech text, l2_definition text,\n`;
  sql += `  l1_translations jsonb, collocations jsonb, l2_synonyms jsonb, example_sentence text, example_l1 text, example_l2 text, l2_mnemonic text, l2_cloze_distractors jsonb, examples jsonb\n`;
  sql += `)\n`;
  sql += `where not exists (\n`;
  sql += `  select 1 from public.cards c2\n`;
  sql += `  where c2.deck_id = dk.id\n`;
  sql += `    and lower(c2.l1_text) = lower(x.l1_text)\n`;
  sql += `    and lower(c2.l2_text) = lower(x.l2_text)\n`;
  sql += `);\n\n`;
}

sql += `commit;\n`;

fs.writeFileSync(OUT, sql, 'utf8');
console.log(`Wrote ${OUT}`);
console.log(`Decks: ${decks.size}, total cards: ${totalCards}, file size: ${(sql.length / 1024).toFixed(1)} KB`);
for (const deck of decks.values()) console.log(`  ${deck.slug}: ${deck.cards.length}`);
